server:
  port: 8095

spring:
  application:
    name: config-client

#添加actuator监控相关的控制
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
  endpoint:
    health:
      show-details: always
  server:        # 指定actuator端口。如果不指定则与系统服务端口一致。建议修改
    port: 8096


