server:
  port: 8081

spring:
  application:
    name: eureka-server

eureka:
  server:
    enable-self-preservation: false      # 测试时关闭自我保护机制，保证不可用服务及时踢出
    eviction-interval-timer-in-ms: 4000

  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


