server:
  port: 7070

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: 163_route
          uri: http://www.163.com/
          predicates:
          - Path=/163